### ISSUE TITLE
Redis: set TTL keys

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfgridclient_proxy#114]
Recent mainnet outage seem to be related to the networking issues we had at the Lochristi DC. This networking outage seems to have broken Yggdrasil, which in turn piled up messages which then made the gridproxy pod hit it's pod limits, which made the redis crash.

As a temporary solution we removed all backlog messages (by removing the redis dumps) and increased the pod limits by 4 (8CPU / 8GB RAM). Obviously this is not a solution for the future.

What could work apparently is to set TTL keys on redis data.
(No expert here, correct me if i'm wrong)

**Comment by AhmedHanafy725** [comment]
closing it as the nodes' info now comes from graphql's DB instead of sending a request to the node over rmb and storing the result in redis.
