### ISSUE TITLE
Support aggregation for the online nodes on statistics endpoint

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgridclient_proxy#116]
issue: https://github.com/threefoldtech/tfchain_explorer/issues/192

**Comment by AhmedHanafy725** [comment]
for online statistics only `/stats?statue=up`

**Comment by mohamedamer453** [comment]
Verified since the current version for [testnet](https://gridproxy.test.grid.tf/version) is `1.4.1` and for [devnet](https://gridproxy.dev.grid.tf/version) `1.5.0`
