### ISSUE TITLE
docs typo

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgridclient_proxy#124]
![image](https://user-images.githubusercontent.com/64129/163188948-f10560cf-5298-45a8-bb9c-eaea18f6f209.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The swagger docs were updated and the typo was fixed.

![image](https://user-images.githubusercontent.com/101194226/200872369-34f71287-fe5a-4fac-918d-a38fbdcfb562.png)
