### ISSUE TITLE
Return result's count for nodes and farms queries on headers

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgridclient_proxy#127]

**Comment by AhmedHanafy725** [comment]
It's not returned by default, but it can be requested with query param `ret_count=true`

**Comment by mohamedamer453** [comment]
Verified since the current version for [testnet](https://gridproxy.test.grid.tf/version) is `1.4.1` and for [devnet](https://gridproxy.dev.grid.tf/version) `1.5.0`
