### ISSUE TITLE
add support for twins and contracts

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgridclient_proxy#133]
### Twins
should be queried by `twinId` or `address`

### Contracts
should be queried by `contractId` or `twinId`, and contain contract type and consumption report

**Comment by mohamedamer453** [comment]
Verified since the current version for [testnet](https://gridproxy.test.grid.tf/version) is `1.4.1` and for [devnet](https://gridproxy.dev.grid.tf/version) `1.5.0`
