### ISSUE TITLE
twins endpoint doesn't return valid json in case of proxy errors

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/tfgridclient_proxy#134]
Example: https://gridproxy.dev.grid.tf/twin/50 shows `{"status": "error", "message": "Post "http://::1:8051/zbus-cmd": dial tcp [::1]:8051: connect: network is unreachable"}`

Was fixed in https://github.com/threefoldtech/rmb_go/issues/28 but the grid proxy errors need to be modified as well

**Comment by mohamedamer453** [comment]
Verified since the current version for [testnet](https://gridproxy.test.grid.tf/version) is `1.4.1` and for [devnet](https://gridproxy.dev.grid.tf/version) `1.5.0`
