### ISSUE TITLE
Add nodes distribution to the stats endpoint

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgridclient_proxy#146]

**Comment by AhmedHanafy725** [comment]
done, but the country may have 2 entries like BE and Belgium.

![image](https://user-images.githubusercontent.com/41957921/170256811-ac2caf40-a82b-4355-a818-5a955d9078a8.png)

**Comment by mohamedamer453** [comment]
Verified on https://gridproxy.dev.grid.tf 
[v1.5.0](https://gridproxy.dev.grid.tf/version)

The [/stats](https://gridproxy.dev.grid.tf/stats) endpoint now contains `nodeDistribution` which includes country the number of nodes available in each country.

![image](https://user-images.githubusercontent.com/101194226/172120373-6e7272c5-a7d9-4db8-8497-f739990a4192.png)

```
{
  "nodes":25,
  "farms":23,
  "countries":4,
  "totalCru":552,
  "totalSru":43438681808896,
  "totalMru":3927599165440,
  "totalHru":239328651048960,
  "publicIps":26,
  "accessNodes":4,
  "gateways":3,
  "twins":115,
  "contracts":3050,
  "nodesDistribution":{
  "Belgium":21,
  "Egypt":1,
  "Germany":1,
  "United States":2
  }
}
```
