### ISSUE TITLE
Auto-restart on db reset

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/tfgridclient_proxy#150]
The grid proxy adds some views on initialization. When the postgres db is reset, it must be restarted manually. There are >=2 ways to handle this:
- watch the db for the view and kill the process if the view is not there
- watch the db for the view and recreate it if the view is not there

**Comment by mariobassem** [comment]
https://github.com/threefoldtech/tfgridclient_proxy/pull/152
