### ISSUE TITLE
Return not-found when the node doesn't exist

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/tfgridclient_proxy#151]
It's a regression from the ORM thing, /nodes/213127398123 returns an empty node, it should throw a proper error instead.

**Comment by mariobassem** [comment]
https://github.com/threefoldtech/tfgridclient_proxy/pull/153

**Comment by AhmedHanafy725** [comment]
**Verified** on version 1.5.9

![image](https://user-images.githubusercontent.com/41957921/190379187-fe53d8b5-e4c6-4062-bb31-f19d1bc31f48.png)
