### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgridclient_proxy#154]
automate releases and push docker image of release to docker hub.

**Comment by mariobassem** [comment]
https://github.com/threefoldtech/tfgridclient_proxy/pull/155

**Comment by mohamedamer453** [comment]
Verified.

A Release Workflow was created in #155 and it runs and builds a docker image for each release. and all previous runs can be checked [here](https://github.com/threefoldtech/tfgridclient_proxy/actions/workflows/release.yml).
