### ISSUE TITLE
Clarifying swagger docs

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/tfgridclient_proxy#159]
- [ ] ipv4 -> Set to "true" to filter nodes with non-empty ipv4 address in their public config
- [x] country -> link to `/stats` endpoint. It contains a nodeDistribution but it's not yet as of now on testnet.
- [x] ~~bytes -> change to gigabytes (GB) on UI~~ (we don't own UI)
- [ ] general usuability review

**Comment by renauter** [comment]
do we have a link to a list of country codes we can use on "Node country filter"?

**Comment by OmarElawady** [comment]
Yes, the [stats](https://gridproxy.dev.grid.tf/stats) endpoint but it's not deployed on testnet yet.

Regarding the bytes to GB modification, it's a breaking change since terraform and typescript depend on it for capacity scheduling. Why was it made this way is because the grid proxy was meant to be used only by software clients, end users on the other hand interact mainly with the explorers and with projects like the weblets and terraform. So it was made to be software-friendly instead of user-friendly.

**Comment by renauter** [comment]
> Yes, the [stats](https://gridproxy.dev.grid.tf/stats) endpoint but it's not deployed on testnet yet.

Ok, is there a plan to deploy it on testnet?

> Regarding the bytes to GB modification, it's a breaking change since terraform and typescript depend on it for capacity scheduling. Why was it made this way is because the grid proxy was meant to be used only by software clients, end users on the other hand interact mainly with the explorers and with projects like the weblets and terraform. So it was made to be software-friendly instead of user-friendly.

I get it, but the UI is only for users and then we call the backend (same for user and software) to get the query result, correct?
I don't see where an interface parameter in bytes can not be converted to GB when read from UI after pushing the "Execute" button

**Comment by OmarElawady** [comment]
@AhmedHanafy725 will update the issue once 1.5.0 tesetnet release is decided (the one containing this modification in /stats endpoint)

Aha, you mean only modifying the UI and keeping the backend as is. This UI is served by a separate project (we don't own) that receives the API types and serves the UI. And this customization is not available in it (AFAIK). Moreover, this UI is meant for end-users and developers to experiment with the API directly. So the matching between this specific UI and the internal types are important to not mislead developers trying it out and building something depending on it.

**Comment by renauter** [comment]
> Aha, you mean only modifying the UI and keeping the backend as is. This UI is served by a separate project (we don't own) that receives the API types and serves the UI. And this customization is not available in it (AFAIK). Moreover, this UI is meant for end-users and developers to experiment with the API directly. So the matching between this specific UI and the internal types are important to not mislead developers trying it out and building something depending on it.

Ah ok
Indeed if we don't own the UI there is nothing to do from our side unless asking for some specific customization eventually...

**Comment by AhmedHanafy725** [comment]
> @AhmedHanafy725 will update the issue once 1.5.0 tesetnet release is decided (the one containing this modification in /stats endpoint)

1.5.1 is already now on mainnet
