### ISSUE TITLE
Getting Error when try to Generate swagger doc files

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgridclient_proxy#160]
following the docs, I tried to generate swagger doc files but to got this error.
```sh
sameh@sameh-inspiron-3576:~/projects/tfgridclient_proxy$ make docs
go mod vendor; swag init -g internal/explorer/server.go --parseVendor; rm -rf vendor
2022/06/21 10:10:16 Generate swagger docs....
2022/06/21 10:10:16 Generate general API Info, search dir:./
2022/06/21 10:10:16 warning: failed to get package name in dir: ./, error: execute go list command, exit status 1, stdout:, stderr:no Go files in /home/sameh/projects/tfgridclient_proxy
2022/06/21 10:10:17 ParseComment error in file /home/sameh/projects/tfgridclient_proxy/internal/explorer/server.go :cannot find type definition: farm
```

**Comment by AhmedHanafy725** [comment]
can you check again? 
I think it's fixed
![image](https://user-images.githubusercontent.com/41957921/194761266-27ec698e-d31a-4481-a4d0-20a38055bc03.png)

**Comment by khaledyoussef24** [comment]
am i missing a dependence or something ?
![Screenshot from 2022-10-30 09-13-01](https://user-images.githubusercontent.com/110984055/198866878-ebf04e95-b4b8-4e9d-bb57-f0628a22d322.png)

**Comment by Omarabdul3ziz** [comment]
Yes, it is fixed, and I just created docs several times after some updates.

@khaledyoussef24 you need to add `swag` from `go/bin` to your `PATH`. try this
```bash
export PATH=$(go env GOPATH)/bin:$PATH
```

**Comment by khaledyoussef24** [comment]
### verified 

**steps made to verify**

1. clone the grid proxy
2. make sure that the go is installed and the swag is installed
3. run the "make dir" command 


![Image](https://user-images.githubusercontent.com/110984055/199257773-771588e0-1eee-4a0a-9a5c-a5daf30f7310.png)
