### ISSUE TITLE
Swagger models and examples need to be revised

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgridclient_proxy#161]
- for example, for `/twins` endpoint the example and the response model show a `farm` where the actual server response is a `twin`/s
![Screenshot from 2022-06-20 12-47-42](https://user-images.githubusercontent.com/42457449/174752061-3bf49911-4ec0-406b-a48a-232df0ece938.png)

- another example, the `node` response model and example response have two fields one for "total_resources" and another for "used_resources", but in the actual server response, these two fields are sub keys inside the "capacity" key.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The swagger docs were updated and the example responses were modified.

### /twins

![image](https://user-images.githubusercontent.com/101194226/200871175-17e4355b-48eb-433f-ac97-0e125695a7d1.png)

### /nodes/{node_id}

the two fields are now inside "capacity"

![image](https://user-images.githubusercontent.com/101194226/200871557-d2477747-fe29-4274-b946-5b4b700f3fed.png)
