### ISSUE TITLE
`nodes` endpoint gives error on QA network

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgridclient_proxy#165]
![Screenshot from 2022-06-21 14-58-37](https://user-images.githubusercontent.com/42457449/174805274-22d96366-c78e-4d1a-8da1-4a56bcf01e63.png)

**Comment by A-Harby** [comment]
`nodes` endpoint seems to work fine now.
The endpoint for `nodes` appears to function properly right now.
https://gridproxy.qa.grid.tf/nodes

![image](https://user-images.githubusercontent.com/109473873/188940270-8416c11c-938e-4482-8148-c889554205a3.png)

**Comment by AhmedHanafy725** [comment]
resolved in #150
