### ISSUE TITLE
`stats` endpoint's status filter does not behave as explained in swagger

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgridclient_proxy#167]
![Screenshot from 2022-06-21 23-58-05](https://user-images.githubusercontent.com/42457449/174904028-60544b8c-b2be-46bb-a7af-9661fec3c60b.png)

from swagger doc, status should have two possible values `up`, and `down`. but only `up` behave correctly, trying `down` as the status will show all nodes. if this is intended, it needs to be explained correctly in the swagger doc.

**Comment by mohamedamer453** [comment]
Verified on devnet.

Both values for he `status` parameter are working now as explained in the docs.

### Up

![image](https://user-images.githubusercontent.com/101194226/200869179-66130289-5aa9-4ece-86f6-1e9a2b40a67c.png)

### Down

![image](https://user-images.githubusercontent.com/101194226/200869444-95049259-5190-4a19-9478-2c22e830a2ea.png)
