### ISSUE TITLE
swagger: `ping` endpoint response is an object/map not a string

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgridclient_proxy#168]
![Screenshot from 2022-06-22 00-05-09](https://user-images.githubusercontent.com/42457449/174904913-5bdc4154-436b-4308-972c-ad7de776d273.png)

`ping` endpoint swagger example response/model is a string, but the actual response is an object, not a string.

if this is intended, please update the swagger doc.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The swagger docs were updated with the correct type the response is now an object instead of a string.

![image](https://user-images.githubusercontent.com/101194226/200860353-fc08be98-bbf1-4a2f-b92e-c62011f2e101.png)
