### ISSUE TITLE
swagger filter param `ret_count` is boolean, not a string.

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgridclient_proxy#170]
in swagger doc, the type of return_count is a string, but the API expected it as boolean.

![Screenshot from 2022-06-22 19-17-25](https://user-images.githubusercontent.com/42457449/175098417-84d04e89-b3ff-477e-bd2e-554945c79ce1.png)

**Comment by A-Harby** [comment]
More clarification and info on what `ret_count` is supposed to perform.
Furthermore, all parameter responses provide the same result (retrieve all).

eg.
https://gridproxy.qa.grid.tf/nodes?ret_count=true 
https://gridproxy.qa.grid.tf/nodes?ret_count=false 
https://gridproxy.qa.grid.tf/nodes?ret_count=1

**Comment by sameh-farouk** [comment]
> More clarification and info on what `ret_count` is supposed to perform. Furthermore, all parameter responses provide the same result (retrieve all).
> 
> eg. https://gridproxy.qa.grid.tf/nodes?ret_count=true https://gridproxy.qa.grid.tf/nodes?ret_count=false https://gridproxy.qa.grid.tf/nodes?ret_count=1

Hi @A-Harby, please check the response headers. if `ret_count` is set to `true` extra info `count`, `pages`, `size` will be returned in the headers.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The swagger docs were updated and the `ret_count` was changed to boolean instead of a string for all of the available endpoints.

![image](https://user-images.githubusercontent.com/101194226/200861260-63d58686-38fe-4b91-870d-f766637ab0e0.png)
