### ISSUE TITLE
swagger doc should include all error responses as well

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgridclient_proxy#171]
swagger doc should include all error responses as well. currently, the success response is only documented.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The swagger docs were updated and now it includes all error responses for each endpoint.

![image](https://user-images.githubusercontent.com/101194226/200867195-834a2d62-e520-4e43-bdb7-38e4c26abbe3.png)

![image](https://user-images.githubusercontent.com/101194226/200867605-727e8629-9d6b-4f94-ae40-31d5ec0d4937.png)

![image](https://user-images.githubusercontent.com/101194226/200867805-b594b7e5-6d4a-4db6-8582-c73d82f19180.png)
