### ISSUE TITLE
Search query cities and countries needs to be case insensitive 

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgridclient_proxy#175]
Search query cities and countries need to be case-sensitive. see original issue [here](https://github.com/threefoldtech/vgrid/issues/11)

**Comment by A-Harby** [comment]
Same goes for Search query for farms name need to be case-sensitive.
In `Node`, `Gateway`, `Farms` endpoints.

eg.
https://gridproxy.qa.grid.tf/farms?name=Freefarm
![image](https://user-images.githubusercontent.com/109473873/188941733-47044d80-5d6c-4806-8270-c3bcb0c07186.png)
https://gridproxy.qa.grid.tf/farms?name=frerfarm
![image](https://user-images.githubusercontent.com/109473873/188941763-bdb46663-1785-4b34-b073-5a856bd7864d.png)

**Comment by Omarabdul3ziz** [comment]
this also should be applied to Farms names.

also, could it be possible to search with a substring of the name. so typing `freefa` should return nodes in `Freefarm` and `Freefarm2` farms

**Comment by mohamedamer453** [comment]
Verified on devnet.

The following endpoints are not case sensitive anymore.

### Country
-  (https://gridproxy.dev.grid.tf/nodes?country=egypt)

   ![image](https://user-images.githubusercontent.com/101194226/200862658-0f440dbc-8388-464a-a64d-a8b26b046009.png)

- (https://gridproxy.dev.grid.tf/gateways?country=belgium)

   ![image](https://user-images.githubusercontent.com/101194226/200865015-ca8f0659-4075-4b84-96e8-05d4474de4ca.png)

### City 

- (https://gridproxy.dev.grid.tf/nodes?city=cairo)

   ![image](https://user-images.githubusercontent.com/101194226/200864000-5f77562a-b8c0-40e0-bbf1-18e3581e4370.png)

- (https://gridproxy.dev.grid.tf/gateways?city=bartlesville)

   ![image](https://user-images.githubusercontent.com/101194226/200865455-8c28fd91-03dc-48fb-9e35-cc58ea5fcab9.png)

### Farm name (https://gridproxy.dev.grid.tf/farms?name=freefarm)

![image](https://user-images.githubusercontent.com/101194226/200864426-e86c92ae-f3b8-4fca-8402-08f6e687ab78.png)
