### ISSUE TITLE
query to get all cities and all countries

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgridclient_proxy#176]
@despiegk was asking [here](https://github.com/threefoldtech/vgrid/issues/11) 
> how can I know anyhow which locations there are, this feature is not very usable
maybe there should be a query where we can get all cities and all countries

**Comment by ramezsaeed** [comment]
https://github.com/threefoldtech/vgrid/issues/11#issuecomment-1179530051
