### ISSUE TITLE
Update querying dedicated nodes to get the nodes with 0 contracts too

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgridclient_proxy#183]
related issue: https://github.com/threefoldtech/tfgrid_dashboard/issues/126

**Comment by AhmedHanafy725** [comment]
in case a node with 0 contracts got rented, there is no way to query these nodes.
as a suggestion, we can add a query to filter the rented nodes

**Comment by mohamedamer453** [comment]
Verified on devnet.

There are 2 new endpoints that were added [`rentable`](https://gridproxy.dev.grid.tf/nodes?rentable=true) which shows all the nodes that can be rented.

![image](https://user-images.githubusercontent.com/101194226/186649483-196fdf2d-4485-471a-8dda-4d9067a87491.png)

and the second endpoint [`rented`](https://gridproxy.dev.grid.tf/nodes?rented=true) shows all the rented nodes.

However the [swagger docs](https://gridproxy.dev.grid.tf/swagger/index.html#/GridProxy/get_nodes) only contains info about the `rentable` endpoint but the `rented` endpoint is not documented there

**Comment by mohamedamer453** [comment]
Verified.

The `rented` endpoint was added to the [swagger docs](https://gridproxy.dev.grid.tf/swagger/index.html#/GridProxy/get_nodes).

![image](https://user-images.githubusercontent.com/101194226/187163432-8209ebd7-478f-4647-9e21-0a9e96ff07e5.png)
