### ISSUE TITLE
Minor correction in repo readme 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgridclient_proxy#189]
`Farms` instide of `nodes`

![image](https://user-images.githubusercontent.com/109473873/185430229-e06215ff-9764-4032-8851-d10c0acca39e.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The typo was fixed.

![image](https://user-images.githubusercontent.com/101194226/200859305-752fabf4-400a-496c-b7b0-2d17b836b72d.png)
