### ISSUE TITLE
add extra parameters to `/nodes` endpoint

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfgridclient_proxy#199]
it will be easier for the projects that use gridproxy like `dashboard/explorer` to add these parameters :
- `twin_id` : the twin id for the node.
- `node_id` : the node id. just another form of `nodes/<node_id>`

**Comment by khaledyoussef24** [comment]
### verified 

it now can take paramters for second query for twind_id and node_id 
steps made to verify
1-open gridproxy
2- add to the url /nodes/<node_id>
3-try using /nodes?node_id=<node_id>
4-try using /nodes?twin_id=<twin_id>
they all should have the same results
 
![Screenshot from 2022-10-30 09-15-52](https://user-images.githubusercontent.com/110984055/198867011-9832cb1c-b129-42a4-932d-4393600558a5.png)
![Screenshot from 2022-10-30 10-00-02](https://user-images.githubusercontent.com/110984055/198868593-542a301c-663d-4996-85d7-9785a7110421.png)
![Screenshot from 2022-10-30 09-58-57](https://user-images.githubusercontent.com/110984055/198868605-40dbcd59-3f03-410c-addc-277190e2e044.png)
