### ISSUE TITLE
Proxying messages to twins has terrible performance

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/tfgridclient_proxy#212]
When sending a message to a twin over the proxy (/twin/<twin_id> endpoint), throughput almost doesn't go above 2 messages per second, regardless of the client side input. Tested by sending 100 requests in parallel and by sending 500 requests in parallel, and there is no noticeable difference between the two. After a while, most requests will get a 504 Gateway Timeout error from the nginx proxy in front.

Behavior is present on both devnet and mainnet

**Comment by sameh-farouk** [comment]
we have a new flow in place now. proxying messages is no more happening via "gridproxy" service. we consider renaming it :)
