### ISSUE TITLE
Swagger docs: incorrect description for the `status` parameter

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgridclient_proxy#224]
### Description

The description for the status parameter needs to updated because now the `status` parameter returns online nodes only when it's set to `up` and offline nodes only when it's set to `down` and the description mentions that `down` returns all up/down nodes.

![image](https://user-images.githubusercontent.com/101194226/201518703-c1f9e67c-1d20-4a6f-abff-7ce9e55c4c46.png)

the incorrect description is available for this parameter in the following endpoints: `gateways`, `nodes`

it's also available in the `stats` endpoint but it's working with the mentioned logic there. `up` for online only, `down` for online/offline

**Comment by xmonader** [comment]
behavior should be 

```
up: online 
down: offline
no filter = all
```
