### ISSUE TITLE
The `state` parameter in the `/contracts` endpoint is case sensitive

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgridclient_proxy#228]
### Description

The `state` parameter in the contracts endpoint is case sensitive. and will not work with the following values `created`, `deleted`,`graceperiod`

![image](https://user-images.githubusercontent.com/101194226/201642311-7175750e-c0ed-45b3-9357-ed75cee8a894.png)

![image](https://user-images.githubusercontent.com/101194226/201642376-79695914-3063-47b8-8969-20b47ee19a58.png)

![image](https://user-images.githubusercontent.com/101194226/201642455-9fb77cbe-a9f0-4c47-bf96-f1c2386c689e.png)

and it only works when it's capitalized and written exactly as mentioned in the docs.

![image](https://user-images.githubusercontent.com/101194226/201642593-81b81c78-563e-46a6-a4e7-94e9586606aa.png)

![image](https://user-images.githubusercontent.com/101194226/201642694-5890a89a-f5db-4489-8f52-bfb2bfa88b25.png)

![image](https://user-images.githubusercontent.com/101194226/201642794-7612d722-bc8d-46cd-957b-4556bc8143fd.png)

**Comment by A-Harby** [comment]
Verified on Devnet
![image](https://user-images.githubusercontent.com/109473873/230770526-15c9652d-e54f-4e33-b191-8cd79fed27b7.png)
![image](https://user-images.githubusercontent.com/109473873/230770537-7f5839b3-2fac-4269-aefe-742bc173393e.png)
![image](https://user-images.githubusercontent.com/109473873/230770569-fb1f789f-a08d-48a7-902f-d9c79eb50005.png)
