### ISSUE TITLE
Set timeout for /twin endpoint on proxy part

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgridclient_proxy#257]
sometimes the node is not responding (maybe a network issue or the rmb went down) and the request takes so long to timeout around 2 mins

related issue: https://github.com/threefoldtech/grid_weblets/issues/1237

**Comment by sameh-farouk** [comment]
PR waiting for review: https://github.com/threefoldtech/tfgridclient_proxy/pull/259

**Comment by Mahmoud-Emad** [comment]
@sameh-farouk 
Same here?

**Comment by sameh-farouk** [comment]
timeout was implemented and is configurable now / default is 30 seconds.


              Verified on devnet

The request timeout was changed and now we wait on the node until we receive a valid response.
also, the error message was changed with the error content.

_Originally posted by @Mahmoud-Emad in https://github.com/threefoldtech/grid_weblets/issues/1258#issuecomment-1403404375_
