### ISSUE TITLE
use query instead of /gateway endpoint

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfgridclient_proxy#260]
as @sameh-farouk suggested [here](https://github.com/threefoldtech/tfgridclient_proxy/pull/252#pullrequestreview-1249200642) gateway is just a node with a `publicConfig` no need to have a separate endpoint and instead we can provide a query on `/nodes` endpoint to list only the gateways

and @AhmedHanafy725 mentioned it is done like that to be compatible with `Grid v2` in the unified explorer.

Since we don't need it anymore we can remove `/gateway` and use `/nodes?is_gateway=true` instead.

Changes should be in the `/api/v2` to avoid breaking changes on the UI clients

**Comment by sameh-farouk** [comment]
Duplicated threefoldtech/tfgrid-sdk-go#52
