### ISSUE TITLE
update zinit version used in the Gridproxy image

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgridclient_proxy#262]
### Description

https://github.com/threefoldtech/tfgridclient_proxy/blob/a9de350f9c9a24d06505f8986c469622ddc883b9/Dockerfile#L27-L28

image use zinit v0.2.6, while the latest version can be found [here](https://github.com/threefoldtech/zinit/releases), is v0.2.10

**Comment by A-Harby** [comment]
Verified 
![image](https://user-images.githubusercontent.com/109473873/215758673-bc4b0d7d-cba4-4da2-a9f1-2bfb03c7255b.png)
