### ISSUE TITLE
updatedAt field needs to be adjusted to be in seconds in the database

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgridclient_proxy#267]
![image](https://user-images.githubusercontent.com/41957921/214243339-4acb6da9-a6bf-4ff4-ba81-11fba53c0baf.png)

**Comment by zaelgohary** [comment]
Verified.
![image](https://user-images.githubusercontent.com/40770501/214550777-62a1c0a7-19d3-4875-8d2b-a50ca889e794.png)

![image](https://user-images.githubusercontent.com/40770501/214550688-f46e1d7c-1f03-4af9-93d9-8447eb09d753.png)
