### ISSUE TITLE
API returns wrong created_at time for contracts

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgridclient_proxy#276]
### Description

API returns wrong created_at time for contracts
created_at in db for contract used to be in ms. now it stored in seconds

we don't need this conversion anymore.
![Screenshot from 2023-01-30 12-52-40](https://user-images.githubusercontent.com/42457449/215462147-52bd5396-4ca8-402d-b1a3-4939bf43fd51.png)

### Steps to reproduce

https://gridproxy.dev.grid.tf/contracts
check `created_at` field
convert the Unix Timestamp to date will show dates back to 1970

### Logs/Alerts

![photo_٢٠٢٣-٠١-٣٠_١٢-٤٠-٣٦](https://user-images.githubusercontent.com/42457449/215462029-06ef8cff-701c-4e64-968a-79158ccd774a.jpg)

**Comment by A-Harby** [comment]
@sameh-farouk is that deployed over all the network or only Devnet?

**Comment by sameh-farouk** [comment]
The new release that contains the fix deployed only to devnet  till now

**Comment by A-Harby** [comment]
Verified on Devnet.
Tried deploying on weblets and list contracts, And creating contract with TS Client and reviewing from grid proxy; and both data is displayed correctly.
https://user-images.githubusercontent.com/109473873/215756625-7c2125c2-676b-485e-83f5-ab8eb570ed8d.png
