### ISSUE TITLE
Dockerfiles, release and consistency improvements

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/tfgridclient_proxy#282]
### Description
There are currently several problems:
- 2 Dockerfiles:
  - This is confusing 
  - Leads to inconsistencies, for example: #279
  - There's no need to, the simpler, the better
- The standard Dockerfile downloads the latest released binary from github.
  - Requires a manual update to the Dockerfile before creating a release ( you have to know this and it's a source of errors)
  - It's not possible to create an image using your own (modified) sources
- The dockerfiles depend on a manually built version of rmb-go/msgbusd that was added to a specific release
  -  An upgrade to a new version requires someone to figure out how to build, build and add an unofficial binary to an rmb-go release
  - That repository is now archived
- The helm chart declares the version both in the chart and in the values file
  - Standard practice is to only declare it in the chart, the setting in the values file is only there to give an end user the opportunity to override.
  - This is unclear for users and an extra source of errors since most dev's only update the version in the chart. 
-  Releases are created by the github action that calls goreleaser
   - It's counter-intuitive and undocumented
   - It generates quite technical release notes, 
   - Even pre-releases are declared as 'latest'. Sure, one could work around this but github 's release management UI already allows you to do that
- The source has an ancient packaged helm chart  and helm repo index.yaml. Just remove them, they are hopelessly outdated anyway
-   While at it, let's use github container registry instead of threefolddev at docker hub to publish docker images to
    - threefolddev is not the place I would search for to find official threefold images
    - integrates nicely with github packages, showing the latest images automatically on the repo github page
    - no need for docker hub secrets 

### Implementation

- Drop the Dockerfile.release
- Build the source in the standard Dockerfile ( there already is a builder stage, use that one or add another if needed)
- Build rmb-go/msgbusd in the Dockerfile
- Replace the release workflow with one that simply builds the Dockerimage and pushes it to ghcr.io. An example can be found at https://github.com/threefoldtech/tfchain_activation_service/blob/master/.github/workflows/publish_container_image.yml ( instead of `images: ghcr.io/${{ github.repository }}`, it would be `images: ghcr.io/threefoldtech/gridproxy`
- use `ghcr.io/threefoldtech/gridproxy` in the helm chart and drop the goreleaser config

**Comment by A-Harby** [comment]
Verified From action workflow https://github.com/threefoldtech/tfgridclient_proxy/actions/workflows/go.yml and readme steps.

**Comment by robvanmieghem** [comment]
Moving it back in verification, as a to do for me

**Comment by robvanmieghem** [comment]
@Omarabdul3ziz I added some remarks in the already merged PR

**Comment by Omarabdul3ziz** [comment]
requested changes is resolved on the mentioned PR
