### ISSUE TITLE
FR: Setting continuous delivery pipeline with helm deploy action to automate the grid proxy deployments

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgridclient_proxy#299]
### Description

Deploying the grid proxy to Kubernetes via a continuous delivery (CD) pipeline simplifies its maintenance and makes updates faster and easier.

### Implementation

These are good options for GitHub action to be used to deploy the help chart
- https://github.com/vimeda/helm or
- https://github.com/WyriHaximus/github-action-helm3

Need to agree on the triggers for different Envs 

### More
simple [example](https://github.com/marketplace/actions/helm-deploy#example) using helm deploy action
another simple [example](https://github.com/WyriHaximus/github-action-helm3#examples) using helm3 action

**Comment by ramezsaeed** [comment]
Wo'nt fix
