### ISSUE TITLE
Sort nodes by rented first when using the available for filter

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgridclient_proxy#311]
when using the `available_for` filter, it returns shared nodes and the dedicated nodes that the user rented them. so it needs to have the rented nodes on the top of the list returned for the user to be able to see and pick them for deployment.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The `available_for` filter was updated to return nodes rented by the user firstly before returning the other nodes.

For example node `12` on devnet is rented by twin `57` 

![image](https://user-images.githubusercontent.com/101194226/230774386-f9e56ce3-6d78-49f3-bf41-8547a9a5e079.png)

so when we search for nodes `available_for` twin `57` then node `12` will be returned as the first node in the list.

![image](https://user-images.githubusercontent.com/101194226/230774342-f0755e1d-f2ce-4429-9c6d-1d1d8ee0a65b.png)
