### ISSUE TITLE
[Explorer] Unify the returned data pattern

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/tfgridclient_proxy#67]
For the data from the explorer endpoints, there is more than one pattern

For example: 
- `/nodes` and `/gateways`: return list directly 
![image](https://user-images.githubusercontent.com/36021484/148055057-1af320c6-2ad8-4c6d-9828-4b1786959454.png)
- `/farms`: return the list also but in `data.farms` obj, which confusing.
![image](https://user-images.githubusercontent.com/36021484/148055361-b8e7b80b-c261-453a-be7b-361cd2372d78.png)

### Suggestion
- Unify all patterns to be the same and better to be like [V2 explorer](https://explorer.testnet.grid.tf/explorer/farms)

**Comment by dmahmouali** [comment]
**_This will be a breaking change for anyone using the explorer._**

**Comment by waleedhammam** [comment]
done in 1.1.0
