### ISSUE TITLE
[explorer] Flatten The node data to be one rich object instead of two objects

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/tfgridclient_proxy#68]
Now, the Explorer provides two objects for the node, one from `/nodes` which has its general data, and one from `nodes/<id>` which has its resources usage.

### Suggestion
- Flatten The node data to be one rich object instead of two objects

**Comment by waleedhammam** [comment]
I think this will be annoying, cause node data is too long with DMI and hypervisor
