### ISSUE TITLE
gridproxy enhancements

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgridclient_proxy#83]
Based on https://github.com/threefoldtech/tfchain_explorer/issues/150

- Add embedded SQLite. 
- fetch all nodes from graphql in chucks (100/request) every 30 minutes and store them in SQLite 
- the resources' information fetched from the nodes should be stored in SQLite (instead of Redis) in the same struct of the nodes fetched from graphql 
- also add a field for node usage(used/total), so we can sort nodes by less usage to have them at the top of this list. 
- Add node queries directly on SQLite
  - free capacity (cru, mru, sru, hru) 
  - country 
  - city
  - farm name
  - farm ids (a list of farm ids)
  - free public ips
  - access nodes v4
  - access nodes v6
  - gateways
  - status 
- all these queries should be paginated with a limit for each page 
- Add endpoint that return the aggregation of all nodes' resources from SQLite 
- any other query can be sent to graphql with a forced limit

**Comment by muhamadazmy** [comment]
Notes:
- the node struct is flattened in a table, so table should have `id`, `farm_id`, `cru`, `sru`, `free_sru`, `free_hru`, etc ... columns 
- proper indexes must be created so searching on the db should be fast (`id` is going to be public key anyway) but we also probably need an index on farm_id, capcity columns and free capacity columns.
- I don't get the `free public ips` this is fetched from the farms not the nodes. (do we need to track this as well)
- Calculation of number of nodes, amount of total capcity etc can be easily done with queries like `select sum(mru), sum(hru), sum(sru), sum(cru) from nodes;` for example. so returning counters will be super fast.

the nodes endpoint i imagine it's something like 
```
HEAD /nodes < returns the totals (sums)
GET /nodes?page=page,(filter=<value>)*
GET /node/<id> <- return full node structure
```

Farms endpoint can work indeed as a pass through to graphql forcing limits and pagination

**Comment by AhmedHanafy725** [comment]
> I don't get the free public ips this is fetched from the farms not the nodes. (do we need to track this as well)

yes, we need to know if the node in a farm that has free public ips for deployments (eg: kubernetes, caprover)

**Comment by muhamadazmy** [comment]
In that case the user start first by finding the farms that has free ips then select nodes from this farm i guess. no? otherwise syncing farm data for free Ips and then joining on the two table to do the query might not be the best solution (because of the syncing of the farms)

**Comment by AhmedHanafy725** [comment]
for free public IPs query 
- on graphql 
```graphql
{
  publicIps(where: {contractId_eq: 0}){
    farm{
      farmId
    }
  }
}
```
- get a set of farmIds from the previous
- then query the nodes with these farmIds

 > Note: this request to graphql will return the first 50 elements only, so we will need to get them all to get all possible farmIds to query the nodes with them.
