### ISSUE TITLE
Pull Or Push, that is the question?

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/tfgridclient_proxy#92]
So the grid proxy (the one used for real time node status) is trying to query nodes status over rmb every few minutes, this won't scale up nicely when we have many nodes, if the list of nodes has nodes that are down or don't exist anymore it will take ages to scan the full list. We tried to implement an async mechanism where u send the query, then the nodes just respond asynchronously so grid proxy does not have to wait and then can just process responses as they come in. This is fine but also won't scale if u have a huge number of nodes and u have to broadcast the same message to nodes in patches of let's say 1000 (there is still tcp timeout which can cause delays in workers that will add up to a long time)

Hence i was thinking for this scale, it's better if the nodes push their status instead. But to avoid centralization, the node will start pushing status if a client did a register to reporting on the node then the node will start reporting status back. 

this will require also the proxy to register to all nodes (and wait for new nodes, etc ...). So instead may be the nodes need to fetch the list of the nodes from somewhere "decentralized" so I thought may be the grid itself. But that's also a little bit problematic because of the new type, and permissions of who can update this (the dao?)

For now I thought may be we can just have a config repo on github which contains the list of the twins per network so we can control it (for now) until the dao is completed

**Comment by AhmedHanafy725** [comment]
closing it as it becomes irrelevant now
