### ISSUE TITLE
Unify the headers send in the requests 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/tfgridclient_proxy#98]
I can see pages header is supported on grid2 but not in grid3 devnet, and when it is supported, it is supported in nodes and gateways, not in the farms. 

so simply we should keep the structure of the request the same on all networks and in both grid2 and grid3 
like this 
![image](https://user-images.githubusercontent.com/46320202/154962141-de55bd29-0491-4747-b2fa-a501adebea04.png)

not like that 
![image](https://user-images.githubusercontent.com/46320202/154962189-985ebbb2-320e-45ab-9465-c529ac804e18.png)

**Comment by RafyAmgadBenjamin** [comment]
after discussion, we reached to 
- we must have the same headers (unified behavior) on all networks(testnet, devnet, mainnet) and elements (nodes, farms, gateways) in grid3 
- we should have an endpoint that apply the filters in the request and apply the pagination also

**Comment by AhmedHanafy725** [comment]
It's already done.
